//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class AcBalance
    {
        #region Primitive Properties
    
        public string AcHead
        {
            get;
            set;
        }
    
        public short Sequence
        {
            get;
            set;
        }
    
        public Nullable<decimal> opbal
        {
            get;
            set;
        }
    
        public Nullable<decimal> dramt
        {
            get;
            set;
        }
    
        public Nullable<decimal> cramt
        {
            get;
            set;
        }

        #endregion

    }
}
