//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class AcSubCategory
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid SocietyID
        {
            get { return _societyID; }
            set
            {
                if (_societyID != value)
                {
                    if (AcCategory != null && AcCategory.SocietyID != value)
                    {
                        AcCategory = null;
                    }
                    if (Society != null && Society.SocietyID != value)
                    {
                        Society = null;
                    }
                    _societyID = value;
                }
            }
        }
        private System.Guid _societyID;
        [Required]
        public virtual System.Guid SubCategoryID
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="Number of  characters cannot be more than 100")]
        [Required]
        public virtual string SubCategory
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid CategoryID
        {
            get { return _categoryID; }
            set
            {
                if (_categoryID != value)
                {
                    if (AcCategory != null && AcCategory.CategoryID != value)
                    {
                        AcCategory = null;
                    }
                    _categoryID = value;
                }
            }
        }
        private System.Guid _categoryID;
        public virtual Nullable<bool> PartDetails
        {
            get;
            set;
        }
        [Required]
        public virtual byte Sequence
        {
            get;
            set;
        }
        public virtual Nullable<bool> Active
        {
            get { return _active; }
            set { _active = value; }
        }
        private Nullable<bool> _active = true;
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual AcCategory AcCategory
        {
            get { return _acCategory; }
            set
            {
                if (!ReferenceEquals(_acCategory, value))
                {
                    var previousValue = _acCategory;
                    _acCategory = value;
                    FixupAcCategory(previousValue);
                }
            }
        }
        private AcCategory _acCategory;
    
        public virtual ICollection<AcHead> AcHeads
        {
            get
            {
                if (_acHeads == null)
                {
                    var newCollection = new FixupCollection<AcHead>();
                    newCollection.CollectionChanged += FixupAcHeads;
                    _acHeads = newCollection;
                }
                return _acHeads;
            }
            set
            {
                if (!ReferenceEquals(_acHeads, value))
                {
                    var previousValue = _acHeads as FixupCollection<AcHead>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAcHeads;
                    }
                    _acHeads = value;
                    var newValue = value as FixupCollection<AcHead>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAcHeads;
                    }
                }
            }
        }
        private ICollection<AcHead> _acHeads;
    
        public virtual Society Society
        {
            get { return _society; }
            set
            {
                if (!ReferenceEquals(_society, value))
                {
                    var previousValue = _society;
                    _society = value;
                    FixupSociety(previousValue);
                }
            }
        }
        private Society _society;

        #endregion

        #region Association Fixup
    
        private void FixupAcCategory(AcCategory previousValue)
        {
            if (previousValue != null && previousValue.AcSubCategories.Contains(this))
            {
                previousValue.AcSubCategories.Remove(this);
            }
    
            if (AcCategory != null)
            {
                if (!AcCategory.AcSubCategories.Contains(this))
                {
                    AcCategory.AcSubCategories.Add(this);
                }
                if (SocietyID != AcCategory.SocietyID)
                {
                    SocietyID = AcCategory.SocietyID;
                }
                if (CategoryID != AcCategory.CategoryID)
                {
                    CategoryID = AcCategory.CategoryID;
                }
            }
        }
    
        private void FixupSociety(Society previousValue)
        {
            if (previousValue != null && previousValue.AcSubCategories.Contains(this))
            {
                previousValue.AcSubCategories.Remove(this);
            }
    
            if (Society != null)
            {
                if (!Society.AcSubCategories.Contains(this))
                {
                    Society.AcSubCategories.Add(this);
                }
                if (SocietyID != Society.SocietyID)
                {
                    SocietyID = Society.SocietyID;
                }
            }
        }
    
        private void FixupAcHeads(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (AcHead item in e.NewItems)
                {
                    item.AcSubCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AcHead item in e.OldItems)
                {
                    if (ReferenceEquals(item.AcSubCategory, this))
                    {
                        item.AcSubCategory = null;
                    }
                }
            }
        }

        #endregion

    }
}
