//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class MemberLedger
    {
        #region Primitive Properties
    
        public System.Guid SocietyBuildingUnitID
        {
            get;
            set;
        }
    
        public System.Guid SocietyMemberID
        {
            get;
            set;
        }
    
        public string BuildingUnit
        {
            get;
            set;
        }
    
        public string Member
        {
            get;
            set;
        }
    
        public string BillNo
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> BillDate
        {
            get;
            set;
        }
    
        public string Particulars
        {
            get;
            set;
        }
    
        public Nullable<decimal> ChgBal
        {
            get;
            set;
        }
    
        public Nullable<decimal> NonChgBal
        {
            get;
            set;
        }
    
        public Nullable<decimal> IntBal
        {
            get;
            set;
        }
    
        public Nullable<decimal> TaxBal
        {
            get;
            set;
        }
    
        public Nullable<decimal> Advance
        {
            get;
            set;
        }
    
        public Nullable<decimal> ChgAmt
        {
            get;
            set;
        }
    
        public Nullable<decimal> NonChgAmt
        {
            get;
            set;
        }
    
        public Nullable<decimal> IntAmt
        {
            get;
            set;
        }
    
        public Nullable<decimal> TaxAmt
        {
            get;
            set;
        }
    
        public Nullable<decimal> AdvBal
        {
            get;
            set;
        }
    
        public System.Guid SocietyBuildingID
        {
            get;
            set;
        }

        #endregion

    }
}
