//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class ParkingType
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid ParkingTypeID
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="Number of  characters cannot be more than 50")]
        [Required]
        public virtual string Type
        {
            get;
            set;
        }
        [Required]
        public virtual bool Active
        {
            get { return _active; }
            set { _active = value; }
        }
        private bool _active = true;
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<SocietyParking> SocietyParkings
        {
            get
            {
                if (_societyParkings == null)
                {
                    var newCollection = new FixupCollection<SocietyParking>();
                    newCollection.CollectionChanged += FixupSocietyParkings;
                    _societyParkings = newCollection;
                }
                return _societyParkings;
            }
            set
            {
                if (!ReferenceEquals(_societyParkings, value))
                {
                    var previousValue = _societyParkings as FixupCollection<SocietyParking>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSocietyParkings;
                    }
                    _societyParkings = value;
                    var newValue = value as FixupCollection<SocietyParking>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSocietyParkings;
                    }
                }
            }
        }
        private ICollection<SocietyParking> _societyParkings;

        #endregion

        #region Association Fixup
    
        private void FixupSocietyParkings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SocietyParking item in e.NewItems)
                {
                    item.ParkingType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SocietyParking item in e.OldItems)
                {
                    if (ReferenceEquals(item.ParkingType, this))
                    {
                        item.ParkingType = null;
                    }
                }
            }
        }

        #endregion

    }
}
