//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class SocietyBuildingUnitChargeHead
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid SocietyBuildingUnitID
        {
            get { return _societyBuildingUnitID; }
            set
            {
                if (_societyBuildingUnitID != value)
                {
                    if (SocietyBuildingUnit != null && SocietyBuildingUnit.SocietyBuildingUnitID != value)
                    {
                        SocietyBuildingUnit = null;
                    }
                    _societyBuildingUnitID = value;
                }
            }
        }
        private System.Guid _societyBuildingUnitID;
        [Required]
        public virtual System.Guid ChargeHeadID
        {
            get;
            set;
        }
        public virtual Nullable<decimal> Rate
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid SocietyBuildingUnitChargeHeadID
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual SocietyBuildingUnit SocietyBuildingUnit
        {
            get { return _societyBuildingUnit; }
            set
            {
                if (!ReferenceEquals(_societyBuildingUnit, value))
                {
                    var previousValue = _societyBuildingUnit;
                    _societyBuildingUnit = value;
                    FixupSocietyBuildingUnit(previousValue);
                }
            }
        }
        private SocietyBuildingUnit _societyBuildingUnit;

        #endregion

        #region Association Fixup
    
        private void FixupSocietyBuildingUnit(SocietyBuildingUnit previousValue)
        {
            if (previousValue != null && previousValue.SocietyBuildingUnitChargeHeads.Contains(this))
            {
                previousValue.SocietyBuildingUnitChargeHeads.Remove(this);
            }
    
            if (SocietyBuildingUnit != null)
            {
                if (!SocietyBuildingUnit.SocietyBuildingUnitChargeHeads.Contains(this))
                {
                    SocietyBuildingUnit.SocietyBuildingUnitChargeHeads.Add(this);
                }
                if (SocietyBuildingUnitID != SocietyBuildingUnit.SocietyBuildingUnitID)
                {
                    SocietyBuildingUnitID = SocietyBuildingUnit.SocietyBuildingUnitID;
                }
            }
        }

        #endregion

    }
}
