//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class SocietyBuilding
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid SocietyBuildingID
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid SocietyID
        {
            get { return _societyID; }
            set
            {
                if (_societyID != value)
                {
                    if (Society != null && Society.SocietyID != value)
                    {
                        Society = null;
                    }
                    _societyID = value;
                }
            }
        }
        private System.Guid _societyID;
    	
        [StringLength(50, ErrorMessage="Number of  characters cannot be more than 50")]
        [Required]
        public virtual string Building
        {
            get;
            set;
        }
        [Required]
        public virtual byte NoOfFloors
        {
            get;
            set;
        }
        public virtual Nullable<bool> Lift
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Society Society
        {
            get { return _society; }
            set
            {
                if (!ReferenceEquals(_society, value))
                {
                    var previousValue = _society;
                    _society = value;
                    FixupSociety(previousValue);
                }
            }
        }
        private Society _society;
    
        public virtual ICollection<SocietyBuildingUnit> SocietyBuildingUnits
        {
            get
            {
                if (_societyBuildingUnits == null)
                {
                    var newCollection = new FixupCollection<SocietyBuildingUnit>();
                    newCollection.CollectionChanged += FixupSocietyBuildingUnits;
                    _societyBuildingUnits = newCollection;
                }
                return _societyBuildingUnits;
            }
            set
            {
                if (!ReferenceEquals(_societyBuildingUnits, value))
                {
                    var previousValue = _societyBuildingUnits as FixupCollection<SocietyBuildingUnit>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSocietyBuildingUnits;
                    }
                    _societyBuildingUnits = value;
                    var newValue = value as FixupCollection<SocietyBuildingUnit>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSocietyBuildingUnits;
                    }
                }
            }
        }
        private ICollection<SocietyBuildingUnit> _societyBuildingUnits;

        #endregion

        #region Association Fixup
    
        private void FixupSociety(Society previousValue)
        {
            if (previousValue != null && previousValue.SocietyBuildings.Contains(this))
            {
                previousValue.SocietyBuildings.Remove(this);
            }
    
            if (Society != null)
            {
                if (!Society.SocietyBuildings.Contains(this))
                {
                    Society.SocietyBuildings.Add(this);
                }
                if (SocietyID != Society.SocietyID)
                {
                    SocietyID = Society.SocietyID;
                }
            }
        }
    
        private void FixupSocietyBuildingUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SocietyBuildingUnit item in e.NewItems)
                {
                    item.SocietyBuilding = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SocietyBuildingUnit item in e.OldItems)
                {
                    if (ReferenceEquals(item.SocietyBuilding, this))
                    {
                        item.SocietyBuilding = null;
                    }
                }
            }
        }

        #endregion

    }
}
