//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class SocietyBillChargeHeadWithHead
    {
        #region Primitive Properties
    
        public System.Guid SocietyBillID
        {
            get;
            set;
        }
    
        public System.Guid ChargeHeadID
        {
            get;
            set;
        }
    
        public string ChargeHead
        {
            get;
            set;
        }
    
        public decimal Amount
        {
            get;
            set;
        }

        #endregion

    }
}
