//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class SocietyBillChargeHead
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid SocietyBillID
        {
            get { return _societyBillID; }
            set
            {
                if (_societyBillID != value)
                {
                    if (SocietyBill != null && SocietyBill.SocietyBillID != value)
                    {
                        SocietyBill = null;
                    }
                    _societyBillID = value;
                }
            }
        }
        private System.Guid _societyBillID;
        [Required]
        public virtual System.Guid ChargeHeadID
        {
            get;
            set;
        }
        [Required]
        public virtual decimal Amount
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual SocietyBill SocietyBill
        {
            get { return _societyBill; }
            set
            {
                if (!ReferenceEquals(_societyBill, value))
                {
                    var previousValue = _societyBill;
                    _societyBill = value;
                    FixupSocietyBill(previousValue);
                }
            }
        }
        private SocietyBill _societyBill;

        #endregion

        #region Association Fixup
    
        private void FixupSocietyBill(SocietyBill previousValue)
        {
            if (previousValue != null && previousValue.SocietyBillChargeHeads.Contains(this))
            {
                previousValue.SocietyBillChargeHeads.Remove(this);
            }
    
            if (SocietyBill != null)
            {
                if (!SocietyBill.SocietyBillChargeHeads.Contains(this))
                {
                    SocietyBill.SocietyBillChargeHeads.Add(this);
                }
                if (SocietyBillID != SocietyBill.SocietyBillID)
                {
                    SocietyBillID = SocietyBill.SocietyBillID;
                }
            }
        }

        #endregion

    }
}
