//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class SocietyParkingWithMember
    {
        #region Primitive Properties
    
        public System.Guid SocietyID
        {
            get;
            set;
        }
    
        public System.Guid SocietyParkingID
        {
            get;
            set;
        }
    
        public string ParkingNo
        {
            get;
            set;
        }
    
        public string ParkingType
        {
            get;
            set;
        }
    
        public string Member
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> TransferredOn
        {
            get;
            set;
        }
    
        public string VehicleNumber
        {
            get;
            set;
        }

        #endregion

    }
}
