//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class StandardChargeHead
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid ChargeHeadID
        {
            get;
            set;
        }
    	
        [StringLength(100, ErrorMessage="Number of  characters cannot be more than 100")]
        [Required]
        public virtual string ChargeHead
        {
            get;
            set;
        }
        [Required]
        public virtual bool ChargeInterest
        {
            get { return _chargeInterest; }
            set { _chargeInterest = value; }
        }
        private bool _chargeInterest = true;
        [Required]
        public virtual System.Guid AcHeadID
        {
            get { return _acHeadID; }
            set
            {
                if (_acHeadID != value)
                {
                    if (StandardAcHead != null && StandardAcHead.AcHeadID != value)
                    {
                        StandardAcHead = null;
                    }
                    _acHeadID = value;
                }
            }
        }
        private System.Guid _acHeadID;
    	
        [StringLength(1, ErrorMessage="Number of  characters cannot be more than 1")]
        public virtual string Nature
        {
            get;
            set;
        }
        [Required]
        public virtual byte Sequence
        {
            get;
            set;
        }
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual StandardAcHead StandardAcHead
        {
            get { return _standardAcHead; }
            set
            {
                if (!ReferenceEquals(_standardAcHead, value))
                {
                    var previousValue = _standardAcHead;
                    _standardAcHead = value;
                    FixupStandardAcHead(previousValue);
                }
            }
        }
        private StandardAcHead _standardAcHead;

        #endregion

        #region Association Fixup
    
        private void FixupStandardAcHead(StandardAcHead previousValue)
        {
            if (previousValue != null && previousValue.StandardChargeHeads.Contains(this))
            {
                previousValue.StandardChargeHeads.Remove(this);
            }
    
            if (StandardAcHead != null)
            {
                if (!StandardAcHead.StandardChargeHeads.Contains(this))
                {
                    StandardAcHead.StandardChargeHeads.Add(this);
                }
                if (AcHeadID != StandardAcHead.AcHeadID)
                {
                    AcHeadID = StandardAcHead.AcHeadID;
                }
            }
        }

        #endregion

    }
}
