//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace CloudSocietyEntities
{
    public partial class UnitType
    {
        #region Primitive Properties
        [Required]
        public virtual System.Guid UnitTypeID
        {
            get;
            set;
        }
    	
        [StringLength(50, ErrorMessage="Number of  characters cannot be more than 50")]
        [Required]
        public virtual string Type
        {
            get;
            set;
        }
        [Required]
        public virtual bool Active
        {
            get { return _active; }
            set { _active = value; }
        }
        private bool _active = true;
        [Required]
        public virtual System.Guid CreatedByID
        {
            get;
            set;
        }
        [Required]
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }
        public virtual Nullable<System.Guid> UpdatedByID
        {
            get;
            set;
        }
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<SocietyBuildingUnit> SocietyBuildingUnits
        {
            get
            {
                if (_societyBuildingUnits == null)
                {
                    var newCollection = new FixupCollection<SocietyBuildingUnit>();
                    newCollection.CollectionChanged += FixupSocietyBuildingUnits;
                    _societyBuildingUnits = newCollection;
                }
                return _societyBuildingUnits;
            }
            set
            {
                if (!ReferenceEquals(_societyBuildingUnits, value))
                {
                    var previousValue = _societyBuildingUnits as FixupCollection<SocietyBuildingUnit>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSocietyBuildingUnits;
                    }
                    _societyBuildingUnits = value;
                    var newValue = value as FixupCollection<SocietyBuildingUnit>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSocietyBuildingUnits;
                    }
                }
            }
        }
        private ICollection<SocietyBuildingUnit> _societyBuildingUnits;
    
        public virtual ICollection<SocietySpecialBill> SocietySpecialBills
        {
            get
            {
                if (_societySpecialBills == null)
                {
                    var newCollection = new FixupCollection<SocietySpecialBill>();
                    newCollection.CollectionChanged += FixupSocietySpecialBills;
                    _societySpecialBills = newCollection;
                }
                return _societySpecialBills;
            }
            set
            {
                if (!ReferenceEquals(_societySpecialBills, value))
                {
                    var previousValue = _societySpecialBills as FixupCollection<SocietySpecialBill>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSocietySpecialBills;
                    }
                    _societySpecialBills = value;
                    var newValue = value as FixupCollection<SocietySpecialBill>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSocietySpecialBills;
                    }
                }
            }
        }
        private ICollection<SocietySpecialBill> _societySpecialBills;

        #endregion

        #region Association Fixup
    
        private void FixupSocietyBuildingUnits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SocietyBuildingUnit item in e.NewItems)
                {
                    item.UnitType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SocietyBuildingUnit item in e.OldItems)
                {
                    if (ReferenceEquals(item.UnitType, this))
                    {
                        item.UnitType = null;
                    }
                }
            }
        }
    
        private void FixupSocietySpecialBills(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SocietySpecialBill item in e.NewItems)
                {
                    item.UnitType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SocietySpecialBill item in e.OldItems)
                {
                    if (ReferenceEquals(item.UnitType, this))
                    {
                        item.UnitType = null;
                    }
                }
            }
        }

        #endregion

    }
}
